spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0ZHUHY0cVp4ajhwWUVhQlAKaU5ycWNtUDFBSVFNcVNYMmxrMWR6eU1XZk51aFJBTkNBQVRnU3ZsNlJFTFhUYkRJVFlFUnE0YUJPdVBNNlJVNQpkZ2lHQ3hMeWRCVUljUU13aVZhRDEzZmpFQUh0SFNHN214YnJqWWNTL2ZzQXBLbFBmUG9kWTRPdwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNaVENDQWd1Z0F3SUJBZ0lSQU5MaWI2TndZY0RweTdOVjB2T3FXNG93Q2dZSUtvWkl6ajBFQXdJd2daMHgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURTVNRGNHQTFVRUN3d3dkR2h2YldGegpRSFJvYjIxaGN5MVVhR2x1YTFCaFpDMUZNVFF0UjJWdUxUY2dLRlJvYjIxaGN5Qk9aM1Y1Wlc0cE1VQXdQZ1lEClZRUURERGR0YTJObGNuUWdkR2h2YldGelFIUm9iMjFoY3kxVWFHbHVhMUJoWkMxRk1UUXRSMlZ1TFRjZ0tGUm8KYjIxaGN5Qk9aM1Y1Wlc0cE1CNFhEVEkyTURReE5UQTNOREExTjFvWERUSTRNRGN4TlRBM05EQTFOMW93WkRFbgpNQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScFptbGpZWFJsTVRrd053WURWUVFMCkREQjBhRzl0WVhOQWRHaHZiV0Z6TFZSb2FXNXJVR0ZrTFVVeE5DMUhaVzR0TnlBb1ZHaHZiV0Z6SUU1bmRYbGwKYmlrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUZ1N2bDZSRUxYVGJESVRZRVJxNGFCT3VQTQo2UlU1ZGdpR0N4THlkQlVJY1FNd2lWYUQxM2ZqRUFIdEhTRzdteGJyalljUy9mc0FwS2xQZlBvZFk0T3dvMlF3CllqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdId1lEVlIwakJCZ3cKRm9BVUJOYmdWSVcxSnZIODFvWEx5Z2xRUzB5R3VSTXdHZ1lEVlIwUkJCTXdFWUlQYkc5allXd3VNSGhrWW1VdQpaR1YyTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUEvVk15YmdiUXNob3NtZ0dPNlRyenNxbFgxSmcwVDBITU5ECmtwRW1tQ3lJQWlFQXFGTHJOR3IzaE92MEdaeEFUNjdyQnZDV3VxbnB6bjlSMXhGVk5xNldScms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNnVENDQWlhZ0F3SUJBZ0lSQUk4c3FRdk9IN09rRWd6TldVb2Qrdkl3Q2dZSUtvWkl6ajBFQXdJd2daMHgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURTVNRGNHQTFVRUN3d3dkR2h2YldGegpRSFJvYjIxaGN5MVVhR2x1YTFCaFpDMUZNVFF0UjJWdUxUY2dLRlJvYjIxaGN5Qk9aM1Y1Wlc0cE1VQXdQZ1lEClZRUURERGR0YTJObGNuUWdkR2h2YldGelFIUm9iMjFoY3kxVWFHbHVhMUJoWkMxRk1UUXRSMlZ1TFRjZ0tGUm8KYjIxaGN5Qk9aM1Y1Wlc0cE1CNFhEVEkyTURReE5UQTNOREExTjFvWERUTTJNRFF4TlRBM05EQTFOMW93Z1oweApIakFjQmdOVkJBb1RGVzFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JEUVRFNU1EY0dBMVVFQ3d3d2RHaHZiV0Z6ClFIUm9iMjFoY3kxVWFHbHVhMUJoWkMxRk1UUXRSMlZ1TFRjZ0tGUm9iMjFoY3lCT1ozVjVaVzRwTVVBd1BnWUQKVlFRREREZHRhMk5sY25RZ2RHaHZiV0Z6UUhSb2IyMWhjeTFVYUdsdWExQmhaQzFGTVRRdFIyVnVMVGNnS0ZSbwpiMjFoY3lCT1ozVjVaVzRwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTVU3VWRZQXIwUXhKCkV2Qm1OUFNMd1Q4dHBmTGIrTjliWjRGVklJTThadHVpRXJKa09mbGI3c1Z4U3dEb1JMVnRIQW1keUdGY3QvTmcKK2cvWDdkNi9wcU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0lFTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFBdwpIUVlEVlIwT0JCWUVGQVRXNEZTRnRTYngvTmFGeThvSlVFdE1ocmtUTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDCklRQ3pwbjFEWVZUVlhOL043MG1KZE9kN0hoRWxWVUhuZ2wwWTdidndYdWp2elFJaEFLcDdzOU8yV1dLV3FIK3UKTld4cmRSdEZaQ0lDL2M3TVBsV01HRVc2Y1NYegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  ssl:
    bundle: web
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie:
        same-site: strict
  # Step 5: End of session cookie configuration